trigger:
  branches:
    include:
      - main

jobs:
- job: Build
  displayName: 'Build Java App'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '11'
      addToPath: true

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'jarFiles'
      targetPath: '$(Pipeline.Workspace)/target'

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
