pool:
  name: Agent1
  demands:
  - msbuild
  - visualstudio

trigger:
  branches:
    include:
    - '*'
pr: none

variables:
- group: Common build variables

name: 1.0.0$(Rev:.r)
steps:
- template: template1.yml

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 5.3.0'
  inputs:
    versionSpec: 5.3.0

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 3.1.100

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: Path\To\Project.sln
    feedsToUse: config
    nugetConfigPath: '$(NugetConfig)'

- task: VSBuild@1
  displayName: 'Build solution Path\To\Project.sln'
  inputs:
    solution: Path\To\Project.sln
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    msbuildArchitecture: x64

- task: DotNetCoreCLI@2
  displayName: 'NetCore Tests'
  inputs:
    command: test
    projects: |
      Path\To\ProjectTests.csproj

- task: VSTest@2
  displayName: 'NetFramework Tests'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\$(BuildConfiguration)\ProjectX.dll
      !**\*ProjectY.dll
      !**\obj\**
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    packagesToPack: '**/*.nuspec'
    versioningScheme: byEnvVar
    versionEnvVar: Version

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'Feed Name'